[package]
name = "matching"
version = "0.1.0"
edition = "2024"

[dependencies]
rust_decimal = "1.39.0"
serde = {version = "1.0.228", features = ["derive"]}
uuid = {version = "1.18.1", features = ["v4"]}
