[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
tokio = {version = "1.48.0", features = ["full"]}
matching = {path = "../matching"}
rust_decimal = "1.39.0"
uuid = {version = "1.18.1", features = ["v4", "serde"]}
serde = {version = "1.0.228", features = ["derive"]}

